export enum Role {
  RELEASE_MANAGER = 'RELEASE_MANAGER',
  STAKE_HOLDER = 'STAKE_HOLDER',
  AUDITOR = 'AUDITOR',
  LEAD_DEVELOPER = 'LEAD_DEVELOPER',
  DEVELOPER = 'DEVELOPER',
  LEAD_QA = 'LEAD_QA',
  QA = 'QA',
}
